#!/bin/python3

import sys
import error
from matrix import SquareMatrix
#from functions import

operations = {
	"EXP": error.help
}

def main(argv):
        if len(argv) == 1 and argv[0] == "-h":
                error.help()
                exit(0)
        if error.error(argv) is 84:
                exit(84)
        matrix = SquareMatrix(argv[1:])
        matrix.display()
        matrix += matrix
        print("\nmatrix *= 2\n")
        matrix.display()
        #operations[argv[0]]()
        exit(0)

if __name__ == "__main__":
    main(sys.argv[1:])