#!/bin/python3

import sys
import error
from Matrix import SquareMatrix
import functions

operations = {
	"EXP": functions.exp,
        "COS": functions.cos,
        "COSH": functions.cosh,
        "SIN": functions.sin,
        "SINH": functions.sinh
}

def main(argv):
        if len(argv) == 1 and argv[0] == "-h":
                error.help()
                exit(0)
        if error.error(argv) is 84:
                exit(84)
        matrix = SquareMatrix(argv[1:])
        computed = operations[argv[0]](matrix)
        computed.display()
        exit(0)

if __name__ == "__main__":
    main(sys.argv[1:])